[package]
name = "rawr"
description = "Reimplement And Watch Revisions, by mapping between codebases and highlighting when upstream changes affect the existing implementation."
authors = ["Thomas Johnson <NTmatter@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT AND Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.79"
gix = "0.57.1"
rusqlite = { version = "0.30.0", features = ["bundled"] }
#syn = "2.0.46"
#quote = "1.0.35"
tree-sitter = "0.20.10"
tree-sitter-bash = "0.20.3"
tree-sitter-c = "0.20.6"
tree-sitter-cpp = "0.20.3"
tree-sitter-rust = "0.20.4"

tree-sitter-traversal = "0.1.2"

[dev-dependencies]

[build-dependencies]
cc="*"
